\updatehighlight{keyvals}
\copyblock{label}#r
\consumeblock{label}#r
\begin{saveblock}{label}#l
\end{savecode}#S
\begin{latexlight}#S
\end{latexlight}#S
\colorlet{name}{specification}
\definecolor{name}{type}{specification}
\hll|text|
\begin{highlightblock}
\end{highlightblock}#S
\begin{hllblock}
\end{hllblock}#S
\hllDelimDollar
\hllDelimParen
